name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake libffi-dev autoconf
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build with Buildozer
      run: |
        # Ép hệ thống tự động đồng ý với tất cả điều khoản SDK bằng tổ hợp lệnh yes
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | buildozer -v android debug
      env:
        # Biến môi trường hỗ trợ buildozer
        ACCEPT_ANDROID_SDK_LICENSES: "y"
        BUILDOZER_ALLOW_KIVY_NEW_DESIGN: "1"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FPS-Helper-APK
        path: bin/*.apk
        
